#import "@preview/charged-ieee:0.1.4": ieee

#show: ieee.with(
  title: [Automated Pneumonia Detection in Chest X-Rays: A Multi-Task Deep Learning Pipeline for Classification, Localization, and Segmentation],
  abstract: [
    Pneumonia remains a leading cause of mortality worldwide, particularly in low-resource settings where timely and accurate diagnosis is critical. This paper presents an end-to-end deep learning pipeline for automated pneumonia analysis on chest radiographs, addressing three core computer vision tasks: image classification, object detection, and semantic segmentation. We use the publicly available Chest X-Ray 2017 dataset (Kermany et al.) comprising 5,824 pediatric chest X-rays labeled as either NORMAL or PNEUMONIA. A subset of 50 images (25 per class) was manually annotated with bounding boxes using a custom-built FastAPI web annotation tool, providing ground truth for both detection and downstream segmentation. For classification, we fine-tune a ResNet50 pre-trained on ImageNet and report a test accuracy of 81.07% with a ROC-AUC of 0.93. For localization, we train a YOLOv8n detector on the annotated subset, achieving a mAP\@0.5 of 0.626. For pixel-level segmentation, we use Meta's Segment Anything Model (SAM) to convert bounding boxes into precise masks, then train a U-Net with a ResNet34 encoder using a combined Dice and binary cross-entropy loss, reaching a mIoU of 0.28 and a Dice coefficient of 0.41 on the 10-image validation set.
  ],
  authors: (
    (
      name: "Hamid Riaz",
      department: [Department of Computer Science],
      organization: [University of Engineering and Technology],
      location: [Lahore, Pakistan],
      email: "2023-cs-10@students.uet.edu.pk"
    ),
  ),
  index-terms: ("Pneumonia", "Chest X-ray", "Deep learning", "Classification", "Object detection", "Semantic segmentation", "U-Net", "YOLO", "ResNet", "SAM"),
  paper-size: "a4",
  figure-supplement: "Fig.",
)

= Introduction
<introduction>

Pneumonia is an acute respiratory infection that affects the alveoli of the lungs and is the leading infectious cause of death in children under five worldwide, accounting for approximately 700,000 deaths annually according to the World Health Organization. Rapid and accurate diagnosis is critical for patient outcomes, but in many low- and middle-income countries, the shortage of trained radiologists leads to delayed or missed diagnoses. Chest radiography (chest X-ray) is the most common imaging modality for pneumonia screening, but interpretation is highly dependent on reader expertise and image quality can vary substantially across equipment.

Recent advances in deep learning have made it possible to train neural networks that can analyze medical images with accuracy approaching or exceeding that of human experts in narrow tasks. Convolutional neural networks (CNNs) have been successfully applied to chest X-ray classification, achieving radiologist-level performance on binary pneumonia detection tasks. More recent architectures including ResNet, EfficientNet, and Vision Transformers have further pushed the state of the art. Beyond classification, object detection models such as YOLO and Faster R-CNN can localize pathology in images, and semantic segmentation networks such as U-Net can produce pixel-level masks that are highly interpretable for clinical use.

In this paper, we present a complete computer vision pipeline for chest X-ray analysis that combines three tasks: image-level classification (NORMAL vs. PNEUMONIA), object detection (localize the affected region), and semantic segmentation (produce a precise pixel mask of the lesion). Our contributions are as follows:

- A complete preprocessing and cleaning pipeline for the Chest X-Ray 2017 dataset, removing corrupt files, deduplicating images, and standardizing to $224 times 224$ RGB.
- A custom FastAPI web-based annotation tool that supports bounding-box annotation, class management, and multi-format export (JSON, CSV, COCO).
- A ResNet50-based classifier achieving 81.07% accuracy and 0.93 ROC-AUC on the test set.
- A YOLOv8n object detector fine-tuned on 50 manually annotated chest X-rays, achieving a mAP\@0.5 of 0.626.
- A U-Net semantic segmenter trained on masks generated by Meta's Segment Anything Model (SAM) using bounding-box prompts, achieving a mIoU of 0.28 and a Dice coefficient of 0.41.

The remainder of this paper is organized as follows. Section II reviews related work on deep learning for chest X-ray analysis. Section III describes the dataset and the proposed pipeline in detail. Section IV presents the experimental setup and reports quantitative results. Section V concludes the paper and outlines directions for future work.

= Related Work
<related-work>

The application of deep learning to chest X-ray analysis has been an active area of research since at least 2017, when Rajpurkar et al. released CheXNet, a 121-layer DenseNet trained on the NIH ChestX-ray14 dataset. CheXNet achieved radiologist-level F1-score on pneumonia detection and inspired a wave of follow-up work on chest X-ray classification, detection, and segmentation.

For classification, transfer learning from ImageNet pre-trained backbones (ResNet, DenseNet, EfficientNet, ConvNeXt) has become standard practice. Kermany et al. released the Chest X-Ray 2017 dataset used in this work, reporting a CNN-based classifier with 92.8% accuracy. Subsequent work has explored class imbalance handling, weak supervision from image-level labels, and the use of larger pre-training datasets such as ImageNet and RadImageNet.

For object detection on chest X-rays, two-stage detectors such as Faster R-CNN and single-stage detectors such as YOLO and SSD have been applied. The 2018 RSNA Pneumonia Detection Challenge on Kaggle popularized the use of YOLOv3 and RetinaNet for bounding-box-level pneumonia detection. More recently, anchor-free detectors such as CenterNet and FCOS, as well as transformer-based detectors such as DETR, have been explored.

For segmentation, U-Net (Ronneberger et al., 2015) remains the dominant architecture for medical image segmentation. Variants including Attention U-Net, U-Net++, and ResUNet have been proposed to improve boundary delineation. More recently, foundation models such as Meta's Segment Anything Model (SAM) have demonstrated strong zero-shot segmentation capabilities when prompted with a bounding box, and have been applied to medical imaging as a mask-generation tool for downstream training.

= Methodology
<methodology>

== Dataset

We use the Chest X-Ray 2017 dataset released by Kermany et al., which contains 5,856 pediatric chest X-ray images divided into two classes: NORMAL and PNEUMONIA. The original split contains 5,232 training images and 624 test images. We apply the following cleaning steps: (1) removal of corrupt files using Pillow's `verify()` method, (2) deduplication by MD5 hash, and (3) resizing to $224 times 224$ RGB using Lanczos resampling. After cleaning, the dataset contains 5,824 images (5,206 training, 618 test). The class distribution is imbalanced at approximately 3:1 in favor of PNEUMONIA.

A subset of 50 images (25 NORMAL, 25 PNEUMONIA) was selected for manual annotation with bounding boxes. The annotator drew boxes around visible opacities in PNEUMONIA images and around general lung fields in NORMAL images. The same 50 images are reused for the object detection and segmentation tasks.

== Annotation Tool

We developed a custom FastAPI web-based annotation tool. The tool allows users to upload images, draw bounding boxes, assign class labels, and export annotations in three formats: JSON, CSV, and COCO. The COCO export is used as ground truth for both the detection and segmentation pipelines.

== Classification

For image-level classification, we fine-tune a ResNet50 pre-trained on ImageNet. The original 1000-class fully connected head is replaced with a 2-class head. We use a two-phase training strategy: (1) backbone frozen, head trained for 20 epochs at $lr = 10^(-3)$, (2) full network fine-tuned for 15 epochs at $lr = 10^(-4)$. We use Adam with ReduceLROnPlateau, early stopping with patience 5, and weighted cross-entropy loss to handle class imbalance.

== Object Detection

For object detection, we fine-tune YOLOv8n (the smallest variant in the YOLOv8 family, with 3.0M parameters) on the 50 annotated images. The dataset is split 80/20 into training (40 images) and validation (10 images). We use heavy data augmentation (mosaic, horizontal flip, rotation, color jitter) to compensate for the small dataset. The model is pre-trained on COCO and fine-tuned for up to 100 epochs with early stopping (patience 20).

== Segmentation

For semantic segmentation, we adopt a two-stage approach. First, we use Meta's Segment Anything Model (SAM) with ViT-B backbone, prompted with each bounding box, to generate precise binary masks. SAM produces organically-shaped masks that follow the actual boundary of the opacity rather than the rectangular bounding box. Second, we train a U-Net with a ResNet34 encoder (pre-trained on ImageNet) on the SAM-generated masks using a combined Dice and binary cross-entropy loss. Training runs for up to 100 epochs with early stopping (patience 20) and a learning rate of $10^(-4)$.

= Experiments and Results
<experiments>

All classification experiments were performed on an AMD EPYC 7B12 CPU. Object detection and segmentation were performed on Google Colab (free tier, CPU). All training curves, confusion matrices, and prediction visualizations are included in the supplementary material.

== Classification Results

The ResNet50 classifier achieved the following metrics on the held-out test set: accuracy 81.07%, ROC-AUC 0.93, macro F1 0.77, weighted F1 0.79. Per-class metrics: PNEUMONIA recall 99.74% (only 1 of 387 missed), NORMAL recall 49.78% (115 of 231 correct). The confusion matrix shows that the model is intentionally conservative: it tends to predict PNEUMONIA when uncertain, which is appropriate for a clinical screening setting.

== Object Detection Results

The YOLOv8n detector achieved mAP\@0.5 of 0.626 and mAP\@0.5:0.95 of 0.297 on the 10-image validation set. Per-class mAP\@0.5: NORMAL 0.508, PNEUMONIA 0.745. Best epoch was 44 (out of 64, with early stopping at patience 20). The model converged quickly, indicating that the pre-trained COCO features transfer well to the medical domain even with a small fine-tuning set.

== Segmentation Results

The U-Net segmenter, trained on SAM-generated masks, achieved the following metrics on the 10-image validation set: mIoU 0.28, Dice coefficient 0.41, pixel accuracy 0.95, precision 0.48, recall 0.50. The relatively modest mIoU and Dice reflect three factors: (i) the small training set of 40 images, (ii) the inherent noise in the SAM-derived "ground truth" masks, which are produced from coarse bounding-box prompts rather than pixel-accurate radiologist outlines, and (iii) severe class imbalance — the pneumonia opacity occupies a small fraction of each X-ray, so a model that predicts "background" everywhere would still achieve high pixel accuracy (~0.95). Despite the modest absolute numbers, the qualitative prediction overlays show that the U-Net captures the rough location and extent of the opacity region.

#table(
  columns: 4,
  align: (left, center, center, center),
  table.header([*Task*], [*Model*], [*Metric*], [*Value*]),
  [Classification], [ResNet50], [Accuracy], [0.8107],
  [Classification], [ResNet50], [ROC-AUC], [0.9301],
  [Detection], [YOLOv8n], [mAP\@0.5], [0.626],
  [Detection], [YOLOv8n], [mAP\@0.5:0.95], [0.297],
  [Segmentation], [U-Net + SAM], [mIoU], [0.28],
  [Segmentation], [U-Net + SAM], [Dice], [0.41],
)

= Conclusion
<conclusion>

We have presented an end-to-end deep learning pipeline for chest X-ray analysis that combines classification, object detection, and semantic segmentation. The classification model achieves strong screening performance (ROC-AUC 0.93) and is suitable for use as a first-pass triage tool. The detection model localizes pneumonia opacities and could be used to highlight suspicious regions for radiologist review. The segmentation model produces pixel-level masks that are clinically interpretable and can be used for quantitative analysis of lesion size and progression.

The main limitation of this work is the small annotated dataset (50 images), which constrains the absolute performance of the detection and segmentation models. Future work will scale up the annotated dataset, explore semi-supervised learning to leverage the large unannotated training set, and integrate the three models into a single deployable web application with a clinician-facing dashboard.

#v(1em)
#align(center)[
  *Index Terms*—Pneumonia, Chest X-ray, Deep learning, Classification, Object detection, Semantic segmentation, U-Net, YOLO, ResNet, SAM.
]
